faces/urls.py
from __future__ import absolute_import


from django.conf.urls import url

from . import views
from django.views.generic import TemplateView

app_name = 'faces'

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name="faces/home.html"), name='home'),
    url(r'^$', views.home, name='home'),

    url(r'^add/$', views.face_add, name='face_add'),
    url(r'^list/$', views.face_list, name='face_list'),
    url(r'^face/(?P<_id>[0-9]+)/$', views.face_detail, name='face_detail'),
    url(r'^face/delete/(?P<_id>[0-9]+)/$', views.face_delete, name='face_delete'),

    url(r'^clean/$', views.clean, name='clean'),

    url(r'^find/$', views.find, name='find'),
    url(r'^misc/$', views.misc, name='misc'),
]

ntechlab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', lambda r: HttpResponseRedirect('faces')),
    url(r'^faces/', include('faces.urls')),

]

faces/forms.py
# coding=utf-8
from __future__ import unicode_literals
from __future__ import absolute_import

from django import forms
from django.core.exceptions import ValidationError


class AddFaceForm(forms.Form):
    photo = forms.ImageField(label='Фото')
    name = forms.CharField(label='Имя')


class FindFaceForm(forms.Form):
    photo = forms.ImageField(label='Выберите файл с фотографией...', required=False)
    url = forms.CharField(label='...или введите URL', required=False)

    n = forms.IntegerField(label='Максимальное количество найденных фотографий', required=True, min_value=1,
                           max_value=50, initial=10)

    threshold = forms.ChoiceField(
        label='Требуемая точность поиска', required=True,
        choices= [
            ['strict', 'Высокая'],
            ['medium', 'Средняя'],
            ['low', 'Низкая'],
        ],
        initial='medium'
    )


    def clean(self):
        check = [self.cleaned_data['photo'], self.cleaned_data['url']]
        if any(check) and not all(check):
            return self.cleaned_data
        raise ValidationError('Выберите файл или URL')

faces/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import absolute_import

import json

from django.http import HttpResponse
from django.shortcuts import render, redirect

from .services import *
from .forms import *


def misc(request):
    error = ''
    gl = ''
    try:
        gl = get_gallery_list()
    except Exception as e:
        error = unicode(e)

    return render(
        request,
        'faces/misc.html',
        {
            'response': unicode(gl),
            'error': error,
        }
    )


def face_add(request):
    if request.method == 'POST':

        form = AddFaceForm(request.POST, request.FILES)

        if form.is_valid():
            try:
                face = create_face(request.FILES['photo'], json.dumps({'name':form.cleaned_data['name']}))
                return redirect('faces:face_detail', face['id'])
            except ServiceException as e:
                form.add_error(None, unicode(e))

    else:
        form = AddFaceForm()

    return render(request, 'faces/face_add.html', {'form': form})


def _json_meta(f):
    try:
        f['meta'] = json.loads(f['meta'])
    except ValueError:
        pass

    return f

def _digforname(f):

    f =_json_meta(f)

    m = f['meta']

    if isinstance(m, (str, unicode)):
        f['name'] = m
    else:
        try:
            f['name'] = m['name']
        except (KeyError, TypeError):
            f['name'] = 'Неизвестный'
    return f

def _digfornames(faces):
    return map(_digforname, faces)

def face_list(request):
    return render(request, 'faces/face_list.html',
                  {'face_list': _digfornames(list_faces()), 'delete': True})

def face_detail(request, _id):
    return render(request, 'faces/face_detail.html', {'face': _digforname(get_face(_id))})


def face_delete(request, _id):
    delete_face(_id)
    return redirect('faces:face_list')


def find(request):
    if request.method == 'POST':
        form = FindFaceForm(request.POST, request.FILES)

        if form.is_valid():


            try:
                faces = _digfornames(
                    identify_face(
                        form.cleaned_data['url'] or request.FILES['photo'],
                        form.cleaned_data['n'],
                        form.cleaned_data['threshold']
                    )
                )

                for f in faces:
                    try:
                        if float(f['confidence']) < 0.9:
                            f['lowconfidence'] = '1'
                    except KeyError:
                        pass

                return render(request, 'faces/face_list.html', {'face_list': faces })
            except ServiceException as e:
                form.add_error(None, unicode(e))

    else:
        form = FindFaceForm()

    return render(request, 'faces/find.html', {'form': form})


def home(request):
    return redirect('faces:face_add')

def clean(request):

    for f in list_faces():
        delete_face(f['id'])

    delete_gallery()

    return redirect('faces:face_add')

faces/templates/faces/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <style>
        .top-buffer { margin-top:20px; }
    </style>

    <title>NTechLab Faces - Тестовое задание</title>
</head>
<body>

<div class="container top-buffer">
    <a href="{% url 'faces:face_add' %}" class="btn btn-primary">Добавить фотографию в базу</a>
    <a href="{% url 'faces:find' %}" class="btn btn-primary">Найти человека по фотографии</a>
    <!--<a href="{% url 'faces:misc' %}" class="btn btn-primary">Misc</a>-->
    <a href="{% url 'faces:face_list' %}" class="btn btn-primary">Список загруженных Вами фотографий</a>

    <a href="{% url 'faces:clean' %}" class="btn btn-danger pull-right">Удалить все загруженные Вами фото</a>

    <hr><br>

    {% block content %}
    {% endblock %}
</div>

</body>
</html>

faces/templates/faces/face_add.html
{% extends 'faces/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h2>Добавить фотографию в базу</h2><hr>


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Отправить</button>
</form>

{% endblock %}

faces/templates/faces/face_detail.html
{% extends 'faces/base.html' %}

{% block content %}
<h2>Информация о фотографии</h2><hr>


<div class="row">
    <div class="col-lg-4">
        <img src="{{face.thumbnail}}" class="img-thumbnail"/>
    </div>
    <div class="col-lg-8">
        <h3>{{face.name}}</h3>
        <hr>
        <!--{{face.meta}}-->

        {% if face.meta.company %}
        <h4>Компания</h4>
        {{face.meta.company}}
        <hr>
        {% endif %}

        {% if face.meta.badge %}
        <h4>Должность</h4>
        {{face.meta.badge}}
        <hr>
        {% endif %}

    </div>
</div>


{% endblock %}

faces/templates/faces/face_list.html
{% extends 'faces/base.html' %}

{% block content %}

<h2>Найденные лица</h2><hr>

{% for f in face_list %}

<a href="{% url 'faces:face_detail' f.id %}">
    <img src="{{ f.thumbnail }}" class="img-thumbnail"/>
    {{ f.name}}


</a>

{% if delete %}
<a href="{% url 'faces:face_delete' f.id %}" class="btn btn-danger pull-right glyphicon glyphicon-remove"></a>
{% endif %}

{% if f.lowconfidence %}
(но это неточно!)
{% endif %}

<hr>

{% endfor %}


{% endblock %}

faces/templates/faces/find.html
{% extends 'faces/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<h2>Найти человека по фотографии</h2><hr>


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Найти</button>
</form>


{% endblock %}

faces/templates/faces/home.html
{% extends 'faces/base.html' %}

{% block content %}



{% endblock %}

<!--{% url 'sm:furniture_render' design.hinges.id 'render' as url %}-->

faces/templates/faces/misc.html
{% extends 'faces/base.html' %}

{% block content %}

Responce:<br>
{{response}}
<br>

Error: <br>
{{error}}
<br>

{% endblock %}